/*******************************************************************************
 * @file pam8302a_hal_dac.h
 * @brief PAM8302A speaker amplifier: SD control + DAC/TIM6/DMA audio output.
 *******************************************************************************
 * @note:
 * Drives the PAM8302A (fixed 24 dB gain, active-low SD) fed from DAC1_OUT1
 * (PA4) through the on-board divider/LPF and AC-coupling network. The amplifier
 * is analog and fixed-gain, so this module only owns two things:
 *
 *   1. SD (shutdown) enable/disable with pop-free sequencing (SPEAKER_SD, PA1).
 *   2. DAC + TIM6-TRGO + DMA audio streaming that feeds the amp input.
 *
 * The hardware divider sets a ~0.8 W ceiling into 8 ohm at full-scale DAC, so
 * full-scale is SAFE: this module never limits amplitude for protection.
 * Volume, gamma, the sunrise ramp, and PCM decode/format all belong to higher
 * layers -- this module plays whatever 12-bit samples it is handed.
 *
 * Sample format: 12-bit right-aligned (DAC_ALIGN_12B_R), i.e. unsigned 0..4095
 * with 2048 = mid-scale (silence / quiescent bias). See amp_pcm16_to_dac12()
 * for a documented conversion helper if callers hold signed 16-bit PCM.
 *
 * Pop-free contract (enforced here):
 *   - Idle (init/enabled, not playing): DAC held at mid-scale, not 0.
 *   - Enable:  mid-scale bias -> settle -> SD high -> stream.
 *   - Disable: glide to mid-scale -> SD low -> return to idle.
 *   - Suspend: hard/fast mute for Stop 2 / coin-cell outage entry.
 *
 * Peripheral setup (GPIO PA1, DAC1, TIM6 TRGO=Update, DMA1_Ch3 circular) is
 * generated by CubeMX (MX_* init). amp_init() only orchestrates those, it does
 * not configure the peripherals itself.
 *******************************************************************************
 */

#ifndef HOPPY_CLOCK__PAM8302A_HAL_DAC_H
#define HOPPY_CLOCK__PAM8302A_HAL_DAC_H

/** Includes. *****************************************************************/

#include "stm32l4xx_hal.h"
#include <stdbool.h>
#include <stddef.h>

/** STM32 port and pin configs. ***********************************************/

extern DAC_HandleTypeDef hdac1;
extern TIM_HandleTypeDef htim6;

// DAC channel feeding the amp (DAC1_OUT1 on PA4).
#define AMP_HDAC hdac1
#define AMP_DAC_CHANNEL DAC_CHANNEL_1

// Sample-rate trigger timer (TIM6 TRGO -> DAC). Runs while the module is
// initialized so the DAC always has a trigger to move DHR -> DOR.
#define AMP_HTIM htim6

// SPEAKER_SD: PAM8302A active-low shutdown. Held low by an external pull-down
// during reset/boot, drive high to enable, low to shut down.
#define AMP_SD_GPIO_PORT GPIOA
#define AMP_SD_GPIO_PIN GPIO_PIN_1

/** Definitions. **************************************************************/

// DAC alignment for all sample data handed to this module.
#define AMP_DAC_ALIGN DAC_ALIGN_12B_R

// 12-bit mid-scale: silence and the quiescent idle bias.
#define AMP_DAC_MIDSCALE 2048u

// Default sample rate. Bench test will finalize among 16000 / 22050 / 32000.
#define AMP_DEFAULT_SAMPLE_RATE_HZ 22050u

// Guard rails for amp_set_sample_rate().
#define AMP_MIN_SAMPLE_RATE_HZ 1000u
#define AMP_MAX_SAMPLE_RATE_HZ 48000u

// DC-bias settle time after applying mid-scale, before SD is driven high.
#define AMP_ENABLE_SETTLE_MS 5u

// Blocking glide-to-mid-scale on disable/stop (click suppression, not UX
// volume). AMP_MUTE_RAMP_STEPS * AMP_MUTE_RAMP_STEP_MS is the total fade time.
#define AMP_MUTE_RAMP_STEPS 32u
#define AMP_MUTE_RAMP_STEP_MS 1u

/** Public types. *************************************************************/

/**
 * @brief Refill callback for double-buffered streaming.
 *
 * Invoked from the DMA half- and transfer-complete interrupts to refill one
 * half of the ring buffer with the next chunk of PCM. Runs in ISR context:
 * keep it short and non-blocking. @p dst points at the half to fill and @p
 * count is the number of 12-bit samples expected. When the source runs dry the
 * callback should fill @p dst with AMP_DAC_MIDSCALE (silence) and request a
 * stop from the application layer.
 */
typedef void (*amp_refill_cb_t)(uint16_t *dst, uint16_t count);

/**
 * @brief Description of a preprogrammed tune / sound effect.
 *
 * Assumed shape of an audio asset stored in (currently undecided) external NOR
 * flash. @p samples may live in RAM, internal flash, or QUADSPI memory-mapped
 * flash -- this module does not assume the medium, it only reads the pointer.
 * For fully in-memory clips use amp_play_clip(), for clips too large to hold at
 * once (length > 65535) stream via amp_play_stream().
 */
typedef struct {
  const uint16_t *samples; // 12-bit right-aligned PCM (DAC_ALIGN_12B_R).
  uint32_t length;         // Number of samples.
  uint32_t sample_rate_hz; // Playback rate. 0 -> keep current rate.
  bool loop;               // true -> loop until stopped, false -> play once.
} amp_clip_t;

/** User implementations into STM32 HAL (overwrite weak HAL functions). *******/

void HAL_DAC_ConvHalfCpltCallbackCh1_pam8302a(DAC_HandleTypeDef *hdac);
void HAL_DAC_ConvCpltCallbackCh1_pam8302a(DAC_HandleTypeDef *hdac);
void HAL_DAC_ErrorCallbackCh1_pam8302a(DAC_HandleTypeDef *hdac);

/** Public functions. *********************************************************/

/**
 * @brief Initialize the amplifier driver to a safe, muted idle state.
 *
 * Assumes the CubeMX MX_* init already ran (GPIO PA1 low, DAC1, TIM6, DMA).
 * Ensures SD is low (amp shut down), programs the default sample rate, starts
 * TIM6, and drives the DAC to mid-scale so the output sits at a quiescent bias.
 * Leaves the amp disabled -- call amp_enable() to un-mute.
 *
 * @return HAL_OK on success, HAL error status otherwise.
 */
HAL_StatusTypeDef amp_init(void);

/**
 * @brief Pop-free power-up of the amplifier.
 *
 * Caller must guarantee the 5V amp rail is up. Re-asserts the mid-scale bias,
 * waits AMP_ENABLE_SETTLE_MS for the AC-coupling network to settle, then drives
 * SD high. Blocks for the settle duration. Playback is started separately with
 * amp_play()/amp_play_clip()/amp_play_stream().
 *
 * @return HAL_OK on success, HAL_ERROR if not initialized.
 */
HAL_StatusTypeDef amp_enable(void);

/**
 * @brief Pop-free shutdown of the amplifier.
 *
 * Stops any playback, glides the DAC to mid-scale, then drives SD low. The DAC
 * and TIM6 keep running at the idle bias so the module can be re-enabled
 * cheaply. Blocks for the mute-ramp duration. Use amp_suspend() for a fast,
 * non-blocking shutdown on power loss.
 *
 * @return HAL_OK on success, HAL_ERROR if not initialized.
 */
HAL_StatusTypeDef amp_disable(void);

/**
 * @brief Start DMA playback from a caller-provided sample buffer.
 *
 * @param samples 12-bit right-aligned PCM (must remain valid for playback).
 * @param length  Number of samples (1..65535, the DMA transfer-count limit).
 * @param loop    true -> circular loop, false -> play once then idle.
 *
 * On a non-looping clip the transfer-complete interrupt returns the output to
 * mid-scale idle automatically. The amp must already be enabled for sound.
 *
 * @return HAL_OK if playback started, HAL_ERROR on bad args / not initialized.
 */
HAL_StatusTypeDef amp_play(const uint16_t *samples, uint16_t length, bool loop);

/**
 * @brief Convenience wrapper: play an amp_clip_t.
 *
 * Applies clip->sample_rate_hz (when non-zero) then calls amp_play(). Intended
 * for short clips held entirely in memory (clip->length <= 65535).
 *
 * @return HAL_OK if playback started, HAL error/HAL_ERROR otherwise.
 */
HAL_StatusTypeDef amp_play_clip(const amp_clip_t *clip);

/**
 * @brief Start gapless double-buffered streaming into a ring buffer.
 *
 * DMA runs circularly over @p ring, @p refill is called from the half- and
 * transfer-complete interrupts to refill each half with the next chunk from the
 * (higher-layer owned) source. Use this once audio streams from flash rather
 * than a single fixed buffer.
 *
 * @param ring      Ring buffer of 12-bit samples, valid for the whole stream.
 * @param total_len Total ring length in samples (even, >= 2).
 * @param refill    Refill callback (see amp_refill_cb_t). Primed once up front.
 *
 * @return HAL_OK if streaming started, HAL_ERROR on bad args / not initialized.
 */
HAL_StatusTypeDef amp_play_stream(uint16_t *ring, uint16_t total_len,
                                  amp_refill_cb_t refill);

/**
 * @brief Stop playback and return the DAC to mid-scale idle.
 *
 * Glides to mid-scale to avoid a click. The amp stays enabled (SD unchanged),
 * call amp_disable() to also mute the amp. Blocks for the mute-ramp duration.
 *
 * @return HAL_OK on success, HAL_ERROR if not initialized.
 */
HAL_StatusTypeDef amp_stop(void);

/**
 * @brief Reconfigure TIM6 for a new sample rate.
 *
 * Reads the live TIM6 clock (so it survives a system clock-profile change) and
 * sets the auto-reload for @p sample_rate_hz. Best called while stopped.
 *
 * @param sample_rate_hz Target rate, AMP_MIN_SAMPLE_RATE_HZ..AMP_MAX_SAMPLE_RATE_HZ.
 * @return HAL_OK on success, HAL_ERROR if out of range / not representable.
 */
HAL_StatusTypeDef amp_set_sample_rate(uint32_t sample_rate_hz);

/**
 * @brief Hard, fast shutdown for Stop 2 / coin-cell outage entry.
 *
 * Drives SD low immediately, aborts DMA, and stops the DAC and TIM6. Does not
 * glide (no time, and the 5V rail is dying anyway). Non-blocking, ISR-safe.
 * After this the module is uninitialized, call amp_init() to bring it back.
 */
void amp_suspend(void);

/**
 * @brief Whether a DMA playback/stream is currently active.
 *
 * @return true if streaming/playing, false if idle, muted, or uninitialized.
 */
bool amp_is_playing(void);

/**
 * @brief Convert one signed 16-bit PCM sample to a 12-bit DAC code.
 *
 * Documented convenience for callers holding signed 16-bit PCM. Maps the full
 * signed range onto 0..4095 with 0 -> mid-scale (2048). 8-bit callers can use
 * (sample << 4) for unsigned, or ((sample ^ 0x80) << 4) for signed.
 *
 * @param sample Signed 16-bit PCM value.
 * @return 12-bit right-aligned DAC code.
 */
static inline uint16_t amp_pcm16_to_dac12(int16_t sample) {
  return (uint16_t)(((int32_t)sample + 32768) >> 4);
}

#endif
